"""Add ExportRecord table

Revision ID: 7d938a7bd701
Revises: eb7ac53d9184
Create Date: 2026-03-24 10:43:18.977090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d938a7bd701'
down_revision: Union[str, None] = 'eb7ac53d9184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('export_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliationrun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exportrecord_export_type'), 'exportrecord', ['export_type'], unique=False)
    op.create_index(op.f('ix_exportrecord_run_id'), 'exportrecord', ['run_id'], unique=False)
    op.create_index(op.f('ix_exportrecord_tenant_id'), 'exportrecord', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exportrecord_tenant_id'), table_name='exportrecord')
    op.drop_index(op.f('ix_exportrecord_run_id'), table_name='exportrecord')
    op.drop_index(op.f('ix_exportrecord_export_type'), table_name='exportrecord')
    op.drop_table('exportrecord')
    # ### end Alembic commands ###
