"""Add indexes for matching engine fields

Revision ID: eb7ac53d9184
Revises: b0352a166d3d
Create Date: 2026-03-24 10:25:05.411083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb7ac53d9184'
down_revision: Union[str, None] = 'b0352a166d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adminentry_description'), 'adminentry', ['description'], unique=False)
    op.create_index(op.f('ix_adminentry_reference_normalized'), 'adminentry', ['reference_normalized'], unique=False)
    op.create_index(op.f('ix_adminentry_reference_raw'), 'adminentry', ['reference_raw'], unique=False)
    op.create_index(op.f('ix_banktransaction_description'), 'banktransaction', ['description'], unique=False)
    op.create_index(op.f('ix_banktransaction_reference_normalized'), 'banktransaction', ['reference_normalized'], unique=False)
    op.create_index(op.f('ix_banktransaction_reference_raw'), 'banktransaction', ['reference_raw'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banktransaction_reference_raw'), table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_reference_normalized'), table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_description'), table_name='banktransaction')
    op.drop_index(op.f('ix_adminentry_reference_raw'), table_name='adminentry')
    op.drop_index(op.f('ix_adminentry_reference_normalized'), table_name='adminentry')
    op.drop_index(op.f('ix_adminentry_description'), table_name='adminentry')
    # ### end Alembic commands ###
