"""Initial migration

Revision ID: ebbe42d1831b
Revises: 
Create Date: 2026-03-20 22:55:04.538589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebbe42d1831b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appuser',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appuser_email'), 'appuser', ['email'], unique=True)
    op.create_index(op.f('ix_appuser_tenant_id'), 'appuser', ['tenant_id'], unique=False)
    op.create_table('fileupload',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fileupload_file_type'), 'fileupload', ['file_type'], unique=False)
    op.create_index(op.f('ix_fileupload_status'), 'fileupload', ['status'], unique=False)
    op.create_index(op.f('ix_fileupload_tenant_id'), 'fileupload', ['tenant_id'], unique=False)
    op.create_table('reconciliationrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliationrun_status'), 'reconciliationrun', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliationrun_tenant_id'), 'reconciliationrun', ['tenant_id'], unique=False)
    op.create_table('adminentry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_row_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['fileupload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminentry_amount'), 'adminentry', ['amount'], unique=False)
    op.create_index(op.f('ix_adminentry_date'), 'adminentry', ['date'], unique=False)
    op.create_index(op.f('ix_adminentry_tenant_id'), 'adminentry', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_adminentry_upload_id'), 'adminentry', ['upload_id'], unique=False)
    op.create_table('auditlogrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlogrecord_event_type'), 'auditlogrecord', ['event_type'], unique=False)
    op.create_index(op.f('ix_auditlogrecord_tenant_id'), 'auditlogrecord', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auditlogrecord_user_id'), 'auditlogrecord', ['user_id'], unique=False)
    op.create_table('banktransaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_row_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['fileupload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banktransaction_amount'), 'banktransaction', ['amount'], unique=False)
    op.create_index(op.f('ix_banktransaction_date'), 'banktransaction', ['date'], unique=False)
    op.create_index(op.f('ix_banktransaction_tenant_id'), 'banktransaction', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_banktransaction_upload_id'), 'banktransaction', ['upload_id'], unique=False)
    op.create_table('usersession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['appuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_session_token'), 'usersession', ['session_token'], unique=True)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('bank_transaction_id', sa.Uuid(), nullable=False),
    sa.Column('admin_entry_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_entry_id'], ['adminentry.id'], ),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['banktransaction.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['appuser.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliationrun.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_admin_entry_id'), 'match', ['admin_entry_id'], unique=False)
    op.create_index(op.f('ix_match_bank_transaction_id'), 'match', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_match_run_id'), 'match', ['run_id'], unique=False)
    op.create_index(op.f('ix_match_score'), 'match', ['score'], unique=False)
    op.create_index(op.f('ix_match_status'), 'match', ['status'], unique=False)
    op.create_index(op.f('ix_match_tenant_id'), 'match', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_tenant_id'), table_name='match')
    op.drop_index(op.f('ix_match_status'), table_name='match')
    op.drop_index(op.f('ix_match_score'), table_name='match')
    op.drop_index(op.f('ix_match_run_id'), table_name='match')
    op.drop_index(op.f('ix_match_bank_transaction_id'), table_name='match')
    op.drop_index(op.f('ix_match_admin_entry_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_session_token'), table_name='usersession')
    op.drop_table('usersession')
    op.drop_index(op.f('ix_banktransaction_upload_id'), table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_tenant_id'), table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_date'), table_name='banktransaction')
    op.drop_index(op.f('ix_banktransaction_amount'), table_name='banktransaction')
    op.drop_table('banktransaction')
    op.drop_index(op.f('ix_auditlogrecord_user_id'), table_name='auditlogrecord')
    op.drop_index(op.f('ix_auditlogrecord_tenant_id'), table_name='auditlogrecord')
    op.drop_index(op.f('ix_auditlogrecord_event_type'), table_name='auditlogrecord')
    op.drop_table('auditlogrecord')
    op.drop_index(op.f('ix_adminentry_upload_id'), table_name='adminentry')
    op.drop_index(op.f('ix_adminentry_tenant_id'), table_name='adminentry')
    op.drop_index(op.f('ix_adminentry_date'), table_name='adminentry')
    op.drop_index(op.f('ix_adminentry_amount'), table_name='adminentry')
    op.drop_table('adminentry')
    op.drop_index(op.f('ix_reconciliationrun_tenant_id'), table_name='reconciliationrun')
    op.drop_index(op.f('ix_reconciliationrun_status'), table_name='reconciliationrun')
    op.drop_table('reconciliationrun')
    op.drop_index(op.f('ix_fileupload_tenant_id'), table_name='fileupload')
    op.drop_index(op.f('ix_fileupload_status'), table_name='fileupload')
    op.drop_index(op.f('ix_fileupload_file_type'), table_name='fileupload')
    op.drop_table('fileupload')
    op.drop_index(op.f('ix_appuser_tenant_id'), table_name='appuser')
    op.drop_index(op.f('ix_appuser_email'), table_name='appuser')
    op.drop_table('appuser')
    op.drop_table('tenant')
    # ### end Alembic commands ###
